# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_block_segmentation.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 432)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 541, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tabFolder = QtWidgets.QWidget()
        self.tabFolder.setObjectName("tabFolder")
        self.label = QtWidgets.QLabel(self.tabFolder)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.label.setObjectName("label")
        self.txtImagesFolder = QtWidgets.QPlainTextEdit(self.tabFolder)
        self.txtImagesFolder.setGeometry(QtCore.QRect(10, 40, 421, 31))
        self.txtImagesFolder.setObjectName("txtImagesFolder")
        self.btnOpenImagesFolder = QtWidgets.QPushButton(self.tabFolder)
        self.btnOpenImagesFolder.setGeometry(QtCore.QRect(440, 40, 87, 29))
        self.btnOpenImagesFolder.setObjectName("btnOpenImagesFolder")
        self.label_2 = QtWidgets.QLabel(self.tabFolder)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 111, 17))
        self.label_2.setObjectName("label_2")
        self.txtDestFolder1 = QtWidgets.QPlainTextEdit(self.tabFolder)
        self.txtDestFolder1.setGeometry(QtCore.QRect(10, 180, 421, 31))
        self.txtDestFolder1.setObjectName("txtDestFolder1")
        self.btnOpenDestFolder1 = QtWidgets.QPushButton(self.tabFolder)
        self.btnOpenDestFolder1.setGeometry(QtCore.QRect(440, 180, 87, 29))
        self.btnOpenDestFolder1.setObjectName("btnOpenDestFolder1")
        self.btnRun1 = QtWidgets.QPushButton(self.tabFolder)
        self.btnRun1.setGeometry(QtCore.QRect(350, 350, 87, 41))
        self.btnRun1.setObjectName("btnRun1")
        self.btnCancel1 = QtWidgets.QPushButton(self.tabFolder)
        self.btnCancel1.setGeometry(QtCore.QRect(440, 350, 87, 41))
        self.btnCancel1.setObjectName("btnCancel1")
        self.btnOpenRefImage1 = QtWidgets.QPushButton(self.tabFolder)
        self.btnOpenRefImage1.setGeometry(QtCore.QRect(440, 110, 87, 29))
        self.btnOpenRefImage1.setObjectName("btnOpenRefImage1")
        self.label_5 = QtWidgets.QLabel(self.tabFolder)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 101, 17))
        self.label_5.setObjectName("label_5")
        self.txtRefImage1 = QtWidgets.QPlainTextEdit(self.tabFolder)
        self.txtRefImage1.setGeometry(QtCore.QRect(10, 110, 421, 31))
        self.txtRefImage1.setObjectName("txtRefImage1")
        self.tabWidget.addTab(self.tabFolder, "")
        self.tabFiles = QtWidgets.QWidget()
        self.tabFiles.setObjectName("tabFiles")
        self.label_3 = QtWidgets.QLabel(self.tabFiles)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 131, 17))
        self.label_3.setObjectName("label_3")
        self.btnSelectImages = QtWidgets.QPushButton(self.tabFiles)
        self.btnSelectImages.setGeometry(QtCore.QRect(440, 100, 87, 29))
        self.btnSelectImages.setObjectName("btnSelectImages")
        self.btnCleanImagesList = QtWidgets.QPushButton(self.tabFiles)
        self.btnCleanImagesList.setGeometry(QtCore.QRect(440, 140, 87, 29))
        self.btnCleanImagesList.setObjectName("btnCleanImagesList")
        self.label_4 = QtWidgets.QLabel(self.tabFiles)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 131, 17))
        self.label_4.setObjectName("label_4")
        self.txtDestFolder2 = QtWidgets.QPlainTextEdit(self.tabFiles)
        self.txtDestFolder2.setGeometry(QtCore.QRect(10, 280, 421, 31))
        self.txtDestFolder2.setObjectName("txtDestFolder2")
        self.btnDestFolder2 = QtWidgets.QPushButton(self.tabFiles)
        self.btnDestFolder2.setGeometry(QtCore.QRect(440, 280, 87, 29))
        self.btnDestFolder2.setObjectName("btnDestFolder2")
        self.btnRun2 = QtWidgets.QPushButton(self.tabFiles)
        self.btnRun2.setGeometry(QtCore.QRect(350, 350, 87, 41))
        self.btnRun2.setObjectName("btnRun2")
        self.btnCancel2 = QtWidgets.QPushButton(self.tabFiles)
        self.btnCancel2.setGeometry(QtCore.QRect(440, 350, 87, 41))
        self.btnCancel2.setObjectName("btnCancel2")
        self.listImages = QtWidgets.QListWidget(self.tabFiles)
        self.listImages.setGeometry(QtCore.QRect(10, 40, 421, 131))
        self.listImages.setObjectName("listImages")
        self.label_6 = QtWidgets.QLabel(self.tabFiles)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 131, 17))
        self.label_6.setObjectName("label_6")
        self.btnOpenRefImage2 = QtWidgets.QPushButton(self.tabFiles)
        self.btnOpenRefImage2.setGeometry(QtCore.QRect(440, 210, 87, 29))
        self.btnOpenRefImage2.setObjectName("btnOpenRefImage2")
        self.txtRefImage2 = QtWidgets.QPlainTextEdit(self.tabFiles)
        self.txtRefImage2.setGeometry(QtCore.QRect(10, 210, 421, 31))
        self.txtRefImage2.setObjectName("txtRefImage2")
        self.tabWidget.addTab(self.tabFiles, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Images folder:"))
        self.btnOpenImagesFolder.setText(_translate("Form", "Open..."))
        self.label_2.setText(_translate("Form", "Destination folder:"))
        self.btnOpenDestFolder1.setText(_translate("Form", "Open..."))
        self.btnRun1.setText(_translate("Form", "Run "))
        self.btnCancel1.setText(_translate("Form", "Cancel"))
        self.btnOpenRefImage1.setText(_translate("Form", "Open..."))
        self.label_5.setText(_translate("Form", "Reference image:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFolder), _translate("Form", "Folder"))
        self.label_3.setText(_translate("Form", "Images to segment:"))
        self.btnSelectImages.setText(_translate("Form", "Open..."))
        self.btnCleanImagesList.setText(_translate("Form", "Clean"))
        self.label_4.setText(_translate("Form", "Destination folder:"))
        self.btnDestFolder2.setText(_translate("Form", "Open..."))
        self.btnRun2.setText(_translate("Form", "Run "))
        self.btnCancel2.setText(_translate("Form", "Cancel"))
        self.label_6.setText(_translate("Form", "Reference image:"))
        self.btnOpenRefImage2.setText(_translate("Form", "Open..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFiles), _translate("Form", "Files"))

